env: "dev"
http_server:
  address: "localhost:8081"
  timeout: 4s
  idle_timeout: 60s
storage:
  postgres:
    dsn: "postgres://wbexaml0db:wbexam@db/wbexaml0db?sslmode=disable"
    max_open_conns: 100
    max_idle_conns: 50
    conn_max_lifetime: 10m
  lru_cache:
    capacity: 50
kafka:
  addresses:
    - "kafka1:29091"
    - "kafka2:29092"
    - "kafka3:29093"
  consumer:
    order_topic: "order-topic"
    order_group: "order-group"