env: "dev"
http_server:
  address: "localhost:8081"
  timeout: 4s
  idle_timeout: 60s
storage:
  postgres:
    dsn: "postgres://wbexaml0db:wbexam@localhost:5432/wbexaml0db?sslmode=disable"
    max_open_conns: 100
    max_idle_conns: 50
    max_idle_time: 10m
  lru_cache:
    capacity: 50
kafka:
  addresses:
    - "localhost:9091"
    - "localhost:9092"
    - "localhost:9093"
  consumer:
    order_topic: "order-topic"
    order_group: "order-group"