env: "dev"
http_server:
  address: "localhost:8081"
  timeout: 4s
  idle_timeout: 60s
storage:
  postgresdb_dsn: "postgres://wbexaml0db:wbexam@localhost:5432/wbexaml0db?sslmode=disable"
lru_cache:
  capacity: 5
kafka:
  brokers:
    broker1_host: "kafka1:29091"
    broker2_host: "kafka2:29092"
    broker3_host: "kafka3:29093"
  consumer:
    order_topic: "order-topic"
    order_group: "order-group"