version: '3.8'

services:
  k6:
    image: grafana/k6:latest
    container_name: k6-load-test
    volumes:
      - ./scripts:/scripts
      - ./results:/results
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    networks:
      - k6-network

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
    volumes:
      - influxdb-data:/var/lib/influxdb
    networks:
      - k6-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb
    networks:
      - k6-network

volumes:
  influxdb-data:
  grafana-data:

networks:
  k6-network:
    driver: bridge